export const AUTH_ERROR_CODES = {
  INVALID_REQUEST: "AUTH_INVALID_REQUEST",
  UNSUPPORTED_COUNTRY: "AUTH_UNSUPPORTED_COUNTRY",
  EMAIL_EXISTS: "AUTH_EMAIL_EXISTS",
  WEAK_PASSWORD: "AUTH_WEAK_PASSWORD",
  INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  UNAUTHORIZED: "AUTH_UNAUTHORIZED",
  PROFILE_NOT_FOUND: "AUTH_PROFILE_NOT_FOUND",
  ACCESS_DENIED: "AUTH_ACCESS_DENIED",
  COUNTRY_NOT_SUPPORTED: "AUTH_COUNTRY_NOT_SUPPORTED",
  ACCOUNT_DISABLED: "AUTH_ACCOUNT_DISABLED",
  SSO_UNAVAILABLE: "AUTH_SSO_UNAVAILABLE",
  SERVER_ERROR: "AUTH_SERVER_ERROR",
} as const;

export type AuthErrorCode = (typeof AUTH_ERROR_CODES)[keyof typeof AUTH_ERROR_CODES];

const AUTH_ERROR_STATUS: Record<AuthErrorCode, number> = {
  AUTH_INVALID_REQUEST: 400,
  AUTH_UNSUPPORTED_COUNTRY: 400,
  AUTH_EMAIL_EXISTS: 409,
  AUTH_WEAK_PASSWORD: 400,
  AUTH_INVALID_CREDENTIALS: 401,
  AUTH_UNAUTHORIZED: 401,
  AUTH_PROFILE_NOT_FOUND: 404,
  AUTH_ACCESS_DENIED: 403,
  AUTH_COUNTRY_NOT_SUPPORTED: 400,
  AUTH_ACCOUNT_DISABLED: 403,
  AUTH_SSO_UNAVAILABLE: 501,
  AUTH_SERVER_ERROR: 500,
};

export const AUTH_LEGACY_ERROR_ALIAS: Partial<Record<AuthErrorCode, string>> = {
  AUTH_INVALID_REQUEST: "AUTH_VALIDATION_FAILED",
  AUTH_UNSUPPORTED_COUNTRY: "AUTH_COUNTRY_NOT_SUPPORTED",
  AUTH_COUNTRY_NOT_SUPPORTED: "AUTH_COUNTRY_NOT_SUPPORTED",
  AUTH_WEAK_PASSWORD: "AUTH_INVALID_PASSWORD_POLICY",
  AUTH_SERVER_ERROR: "AUTH_INTERNAL_ERROR",
};

export class AuthError extends Error {
  readonly code: AuthErrorCode;
  readonly status: number;

  constructor(code: AuthErrorCode, message: string, status?: number) {
    super(message);
    this.name = "AuthError";
    this.code = code;
    this.status = status ?? AUTH_ERROR_STATUS[code] ?? 500;
  }
}

export function isAuthError(error: unknown): error is AuthError {
  return error instanceof AuthError;
}
