export const AUTH_AUDIT_EVENT_TYPE = {
  SIGNUP_ATTEMPT: "SIGNUP_ATTEMPT",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_FAILURE: "SIGNUP_FAILURE",
  LOGIN_ATTEMPT: "LOGIN_ATTEMPT",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  SSO_CLICK_UNAVAILABLE: "SSO_CLICK_UNAVAILABLE",
} as const;

export const AUTH_AUDIT_STATUS = {
  SUCCESS: "SUCCESS",
  FAILURE: "FAILURE",
} as const;
